In [31]:
import test
import numpy as np

In [24]:
import pyximport; pyximport.install()
import test

In [25]:
mylist = [1,2,3]
for i in mylist:
    print(i)

1
2
3


In [26]:
for i in mylist:
    print(i)

1
2
3


In [27]:
mygen = (x for x in range(1,3))
for j in mygen :
    print(j)

1
2


In [28]:
for j in mygen :
    print(j)

TypeError: 'generator' object is not callable

In [32]:
def sliding_window(image, stepSize, windowSize):
	# slide a window across the image
	for y in range(0, image.shape[0], stepSize):
		for x in range(0, image.shape[1], stepSize):
			# yield the current window
			yield (x, y, image[y:y + windowSize[1], x:x + windowSize[0]])


def singlefilter(img,step,windowsize,tresh):
    img2= img
    for (x, y, window) in sliding_window(img2, stepSize=step, windowSize=windowsize):
        if(np.count_nonzero(window))>=tresh:
            pass
        else :
            img2[x,y]=0
    return img2

In [52]:
mytest = np.zeros((100,100),np.uint16)

In [38]:
for i in range(0,100):
    for j in range(0,100):
        mytest[i,j]=i*j+j


In [66]:
mytest[np.random.choice(20, 100),np.random.choice(20, 100)]=255
mytest

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0, 255,   0, ..., 255,   0,   0],
       [  0,   0, 255, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ..., 255,   0,   0]], dtype=uint16)

In [50]:
mytest[0:3,0:3]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint16)

In [69]:
for i in range(1,99):
    for j in range(1,99):
        if np.count_nonzero(mytest[i-1:i+2,j-1:j+2])>=2:
            pass
        else :
            mytest[i,j]=0
        

In [73]:
def singlenoisefilter(pic2d,size,thresh):
    for i in range(1,size-1):
        for j in range(1,size-1):
            if np.count_nonzero(pic2d[i-1:i+2,j-1:j+2])>=thresh:
                pass
            else :
                pic2d[i,j]=0
        

In [74]:
singlenoisefilter(mytest,100,2)

In [75]:
import myfilters

In [76]:
singlenoisefilter(mytest,100,2)

In [77]:
mytest[0,:]

array([  0,   0,   0,   0,   0, 255, 255, 255, 255,   0,   0,   0,   0,
       255, 255, 255,   0,   0,   0,   0,   0,   0, 255,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 255,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0, 255,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 255,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 255,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [78]:
mytest = np.zeros((10,10),np.uint8)

In [86]:
mytest

array([[1, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [80]:
mytest[0,0]=1
mytest[0,1]=2
mytest[1,0]=3
mytest[1,1]=4

In [82]:
mytest[0,:]

array([1, 2, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [85]:
mytest[:,0]

array([1, 3, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [87]:
mytest[9,0]=5

In [88]:
mytest

array([[1, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [89]:
mytest[9,:]

array([5, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [90]:
mytest[:,9]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)